In [1]:
import numpy as np

In [4]:
a = np.array([[1,2,3,4,6],[12,23,12,34,23]])
a**2

array([[   1,    4,    9,   16,   36],
       [ 144,  529,  144, 1156,  529]])

In [6]:
b = np.array([[5,6,7,8,9], [1,23,4,5,6]])
print(a+b)
print(a-b)
print(a/b)
print(a//b)
print(a*b)

[[ 6  8 10 12 15]
 [13 46 16 39 29]]
[[-4 -4 -4 -4 -3]
 [11  0  8 29 17]]
[[ 0.2         0.33333333  0.42857143  0.5         0.66666667]
 [12.          1.          3.          6.8         3.83333333]]
[[ 0  0  0  0  0]
 [12  1  3  6  3]]
[[  5  12  21  32  54]
 [ 12 529  48 170 138]]


In [7]:
np.cos(a)


array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.96017029],
       [ 0.84385396, -0.53283302,  0.84385396, -0.84857027, -0.53283302]])

In [8]:
np.sin(b)

array([[-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [ 0.84147098, -0.8462204 , -0.7568025 , -0.95892427, -0.2794155 ]])

In [9]:
np.tanh(a)

array([[0.76159416, 0.96402758, 0.99505475, 0.9993293 , 0.99998771],
       [1.        , 1.        , 1.        , 1.        , 1.        ]])

In [45]:
# Matrix Multiplication: Normal multiplication performs element by element multiplication. While matmul performs matrix multiplication
x = np.full((2,3),3)
y = np.random.randint(10,100,size=(3,2))
print(np.matmul(x,y))

[[429 591]
 [429 591]]


In [47]:
z =  np.array([[1,2,3], [2,3,4], [3,4,5]])
print(z)
print(np.linalg.det(z))

[[1 2 3]
 [2 3 4]
 [3 4 5]]
-7.401486830834414e-17


In [49]:
# Statistics
stats = np.array([[1,23,4],[3,4,5]])
print(stats)

[[ 1 23  4]
 [ 3  4  5]]


In [53]:
np.min(stats, axis = 0)

array([1, 4, 4])

In [51]:
np.max(stats)

np.int64(23)

In [54]:
np.min(stats, axis = 1)

array([1, 3])

In [55]:
np.cos(a)

array([[-0.9899925, -0.9899925, -0.9899925, -0.9899925],
       [-0.9899925, -0.9899925, -0.9899925, -0.9899925]])

In [59]:
# statistics
# If axis = 0, then it  means that each column
x = np.array([[1,2,4,5,6], [1,2,3,4,5]])
y = np.array([[2,34,5,6,3],[1,2,3,4,5]])
np.max(x, axis = 0)

array([1, 2, 4, 5, 6])

In [60]:
# If axis = 1, then it means each row
np.max(x, axis = 1)

array([6, 5])

In [61]:
np.min(y,axis = 1)

array([2, 1])

In [65]:
# Sum:
print(np.sum(x))
print(np.sum(x, axis= 1)) # Sum of each row
print(np.sum(x, axis= 0)) # Sum of each column

33
[18 15]
[ 2  4  7  9 11]
