In [1]:
import numpy as np

In [32]:
file_data = np.genfromtxt("data.txt", delimiter=",")
print(file_data)

[[  1.   2.   3.   4.   5.   6.   7.   8.   6.]
 [  2.  23.   3.  44.   5.  54.  56.  32.   2.]
 [  3.   4. 454.  43.  23.  32. 323.   2.   4.]
 [  3.   4. 454.  43.  23.  32. 323.   2.   4.]
 [  3.   4. 454.  43.  23.  32. 323.   3.   4.]
 [  3.   4. 454.  43.  23.  32. 323.   3.   5.]]


### Boolean Masking and Advanced Indexing

In [33]:
# Find the filedata which has values greater than 50
print(file_data)

[[  1.   2.   3.   4.   5.   6.   7.   8.   6.]
 [  2.  23.   3.  44.   5.  54.  56.  32.   2.]
 [  3.   4. 454.  43.  23.  32. 323.   2.   4.]
 [  3.   4. 454.  43.  23.  32. 323.   2.   4.]
 [  3.   4. 454.  43.  23.  32. 323.   3.   4.]
 [  3.   4. 454.  43.  23.  32. 323.   3.   5.]]


In [34]:
# This shows all the values which has values greater than 50
file_data[file_data>50]

array([ 54.,  56., 454., 323., 454., 323., 454., 323., 454., 323.])

In [36]:
#Tells if any column has values greater than 50
np.any(file_data>50,  axis = 0)

array([False, False,  True, False, False,  True,  True, False, False])

In [37]:
# If all column / row has values greater than 50
np.all( file_data>30, axis  = 1)

array([False, False, False, False, False, False])

In [40]:
# Multiple conditions:
(file_data > 50) & (file_data < 100)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True,  True, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False]])

In [ ]:
# Negation:
print(~((file_data > 50) & (file_data < 100)))