In [3]:
import numpy as np

In [10]:
a = np.array([1.0, 2.0, 3.0], dtype = "int16")
a.dtype

dtype('int16')

In [18]:
# 2D Arrays
b = np.array([
    [1,2,3,4,5], 
    [2,3,4,5,6], 
    [5,6,78,8,9], 
    [21,44,212,34,45]])
b.shape

(4, 5)

In [19]:
# Get a specific element -> 212
print(b[3][2])

212


In [20]:
# Get a specific row:
print(b[1,:])

# Get a specific column:
print(b[:,2])

[2 3 4 5 6]
[  3   4  78 212]


In [23]:
# Get a sub array using slicing:
# Prints the sliced sub array in the format - startIndex:endIndex:stepValue
print(b[1, 0:-1:2])

[2 4]


In [24]:
# Change a value of the array:
b[1][2] = 10
b

array([[  1,   2,   3,   4,   5],
       [  2,   3,  10,   5,   6],
       [  5,   6,  78,   8,   9],
       [ 21,  44, 212,  34,  45]])

In [25]:
# Changes the entire row
b[1,:] = 3
print(b)

[[  1   2   3   4   5]
 [  3   3   3   3   3]
 [  5   6  78   8   9]
 [ 21  44 212  34  45]]


In [29]:
# Replace in a 2D array:
b[:,2] = [1,23,33,12]
b

array([[ 1,  2,  1,  4,  5],
       [ 3,  3, 23,  3,  3],
       [ 5,  6, 33,  8,  9],
       [21, 44, 12, 34, 45]])

In [7]:
# Access specific rows and columns
x = np.array([[1,2,3,4,5],[6,7,4,89,3],[12,12,13,45,67],[45,6,64,32,56]])
print(x)

print(x[[0,1,2],[1,2,3]])

print(x[[0,2,3],3:])

[[ 1  2  3  4  5]
 [ 6  7  4 89  3]
 [12 12 13 45 67]
 [45  6 64 32 56]]
[ 2  4 45]
[[ 4  5]
 [45 67]
 [32 56]]


In [26]:
#3D Arrays:
c = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [10,11,12],
        [11.1,12,13]
    ]
]) 
print(c)


[[[ 1.   2.   3. ]
  [ 4.   5.   6. ]]

 [[10.  11.  12. ]
  [11.1 12.  13. ]]]


In [17]:
print(c.ndim)
print(c.dtype)
print(c.itemsize)
print(c.size)
print(c.nbytes)
print(c.shape)

3
int32
4
12
48
(2, 2, 3)


In [27]:
# Change data in a 3D array: (Work outside in)
c[1,1,0] = 11
print(c)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[10. 11. 12.]
  [11. 12. 13.]]]


In [30]:
# Replace in 3D:
#But if the replacement value does not have the same dimensions  - then throws a ValueError
c[:,1,:] = [[1,2,3], [4,5,6]]
print(c)

[[[ 1.  2.  3.]
  [ 1.  2.  3.]]

 [[10. 11. 12.]
  [ 4.  5.  6.]]]
