In [14]:
import numpy as np

In [15]:
# One dimensional array
a = np.array([1,2,3])
print(a)
print(a.shape)
print(a.dtype)

[1 2 3]
(3,)
int64


In [25]:
#Two dimensional arrays:
b = np.array([[1.0 , 2.0, 3.0], [4.0 , 5.0 , 6.0]])
print(b)
print(b.shape)
print(b.dtype)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
float64


In [17]:
# Length/Total number of elements
a.size

3

In [18]:
b.size

6

In [19]:
#Number of bytes
a.itemsize

8

In [20]:
b.itemsize

8

In [21]:
#Total Size - Can be calculated as the product of size and itemsize
a.size * a.itemsize

24

In [22]:
#Other way is to use the nbytes
a.nbytes

24

In [23]:
c = np.array([2,4,6,7,8] , dtype ="int16")
print(c.dtype)
print(c.shape)
print(c.ndim)
print(c.itemsize)
print(c.size)
print(c.nbytes)

int16
(5,)
1
2
5
10
