Numpy - Different forms of array creation

In [1]:
import numpy as np

In [3]:
# All zeroes matrix:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.zeros((2,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
# All one datatype:
np.ones((2,2,3), dtype = "int32")

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [18]:
# Any other number - full
np.full((2,3), 90, dtype = "int16")

array([[90, 90, 90],
       [90, 90, 90]], dtype=int16)

In [21]:
a = np.array([[21,32,32], [21,34,23]])

In [22]:
# full using existing array shape:
np.full(a.shape,40)

array([[40, 40, 40],
       [40, 40, 40]])

In [23]:
# Full like:
np.full_like(a, 40)

array([[40, 40, 40],
       [40, 40, 40]])

In [24]:
# Random decimal numbers:
np.random.rand(2,3)

array([[0.28266758, 0.21382671, 0.7164033 ],
       [0.89898036, 0.14100574, 0.57697475]])

In [27]:
# Random  Sample
np.random.random_sample(a.shape)

array([[0.50124468, 0.6661957 , 0.34678924],
       [0.03700502, 0.0354421 , 0.36685799]])

In [28]:
np.ones(a.shape)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
# Random Int values:
np.random.randint(-10, 100, size = (2,3,3))

array([[[88, 38, 50],
        [99, 40, -2],
        [98, 28, 43]],

       [[13, 43, 80],
        [69, 26, 17],
        [81, 13, 22]]])

In [35]:
# Identity Matrix:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
#Repeat an array:
arr = np.array([[1,2,4]])
np.repeat(arr,3,axis  = 0)

array([[1, 2, 4],
       [1, 2, 4],
       [1, 2, 4]])

In [48]:
a =  np.zeros((5,5), dtype = "int32")
a[0,:] = 1
a[:,0] = 1
a[4,:] = 1
a[:,4] = 1
a[2,2] = 9
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [50]:
b = np.ones((5,5), dtype= "int32")
c = np.zeros((3,3))
c[1,1] = 9
b[1:-1, 1:-1] = c
print(b)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
