In [1]:
import numpy as np
from numpy.ma.core import shape
from numpy.ma.extras import hstack

In [2]:
before = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(before)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
# Reshaping will work as long we have the same number of value (size) in the array:

print(before.size)
print(before.shape)
after = before.reshape(2,5,1)
print(after)

10
(2, 5)
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]


In [8]:
# Vertical stacking vectors:
v1 = np.array([1,2,3,5])
v2 = np.array([2,3,4,56])
np.vstack([v1,v2,v2,v1,v2])

array([[ 1,  2,  3,  5],
       [ 2,  3,  4, 56],
       [ 2,  3,  4, 56],
       [ 1,  2,  3,  5],
       [ 2,  3,  4, 56]])

In [14]:
# Horizontal stack:
h1 = np.ones((2,3))
h2 = np.random.randint(1,100, size=(2,5))
np.hstack([h1,h2])

array([[ 1.,  1.,  1.,  5., 83., 17., 16., 69.],
       [ 1.,  1.,  1., 75., 92., 94., 47., 49.]])